# Generated by Django 5.0.7 on 2024-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('next_followup_date', models.DateField()),
                ('additional_data', models.CharField(max_length=255)),
            ],
        ),
    ]
